-- ===============================================
-- BUZZIFY DATABASE SETUP
-- ===============================================
-- The current app does not require any custom database tables.
-- Supabase is only used for Auth, and generation history is stored
-- in the user's browser localStorage on each device.
--
-- You only need to configure Supabase Auth in the dashboard and set:
-- - NEXT_PUBLIC_SUPABASE_URL
-- - NEXT_PUBLIC_SUPABASE_ANON_KEY
